### ISSUE TITLE
Freezing occurs frequently since ver 4.424.0 released

### ISSUE THREAD

**Issue by lyncher48** [Reetus/ClassicAssist#406]
I think classicassist send wrong packets or sth.

**Comment by Reetus** [comment]
ClassicUO Version: ?
Client Version: ?
Shard: ?

**Comment by lyncher48** [comment]
I am so sorry. It was my problem. Can you close this issue?

**Comment by Reetus** [comment]
I see from the macro you submitted, that the shard is Margo, I was also having issues today before the shard restarted...

I believe it's a shard/ServUO issue, CA has protection for when packet sizes are incorrect, as in...

* it's a fixed length packet and the byte array length is not the same
* it's a variable size packet and the byte array length isn't the same as the length is pos[1] << 8 | pos[2]

And I don't think plugin could cause this issue because packets are not added to the receive buffer, they're just processed as they're sent

**Comment by lyncher48** [comment]
Yes. You are totally right. It was a shard problem. Fortunately, this issue was solved. Thank you for your detailed explanations.
