### ISSUE TITLE
Agent/Loot

### ISSUE THREAD

**Issue by honestaly** [Reetus/ClassicAssist#419]
**Is your feature request related to a problem? Please describe.**
I want to setup Auto Loot rules to grab artifacts that don't have the increased weight (50 stone ones)
However Weight isn't a built in property and each time I tried to add it as a custom one, it generates a new name?

**Describe the solution you'd like**
Add Weight as a property

**Describe alternatives you've considered**
I tried importing the custom trait... it looks like this... and the property name seems to change if I try to import it from a different item.

![image](https://github.com/Reetus/ClassicAssist/assets/88744339/7274e390-1d73-4027-8984-17d6568cacd1)

**Additional context**
I'm also not exactly sure if the Legendary Artifact property should be X, or == 1 or something else.

**Comment by Reetus** [comment]
![image](https://github.com/Reetus/ClassicAssist/assets/6239195/50aba053-a670-4994-a142-c01e8619c419)

I think the issue is it uses the 788 property for when the weight is 1 and the 789 property for anything else?

You should've been fine with multiple entries for stone and stones, but I have added it as a property, matching any of the 3 seen in that list...

When the property has no arguments, it doesn't matter what the operator and value is, except X which means not present...

So, 'Legendary Artifact' == 0 is fine to match items with 'Legendary Artifact' property...

You can test your entries in the Debug menu, and I recommend doing so for confidence that they're correct...

![image](https://github.com/Reetus/ClassicAssist/assets/6239195/8640fc23-891c-45d6-9cd4-e58422950cfe)
